### ISSUE TITLE
vip专辑某些文件可能不能下载

### ISSUE THREAD

**Issue by xiatian12345** [Diaoxiaozhang/Ximalaya-Downloader#19]
下载整个vip专辑资源的时候，如果某些文件标记了试听，则会导致该文件不能下载（但是在浏览器端可以通过嗅探工具等手动下载成功）

**Comment by Diaoxiaozhang** [comment]
我在自己测试时未发现过这个问题，请提供日志文件方便我进行错误排查

**Comment by Diaoxiaozhang** [comment]
你这个问题挺奇怪的，是只有下载vip专辑时才会出现这个问题吗？

**Comment by Diaoxiaozhang** [comment]
看报错的话是同时打开的网络连接数过多，但是我这边没法复现这个问题，可能是你的网络的问题？我等下改下代码，做个并发数量的限制，然后你再测试一下吧

**Comment by Diaoxiaozhang** [comment]
[Ximalaya-Downloader.zip](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11580950/Ximalaya-Downloader.zip)
你看看把这个解压出来测试一下

**Comment by xiatian12345** [comment]
> 你这个问题挺奇怪的，是只有下载vip专辑时才会出现这个问题吗？

不是的，应该是文件数量多就会出现

**Comment by Diaoxiaozhang** [comment]
你把我前面发给你的压缩包下载下来解压，里面是我改过代码后的程序，你试试还会不会有错误

**Comment by xiatian12345** [comment]
> [Ximalaya-Downloader.zip](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11580950/Ximalaya-Downloader.zip) 你看看把这个解压出来测试一下

解压出来是windows应用呀，我用的mac没有相关环境，只吧main.py发出就可以了

**Comment by Diaoxiaozhang** [comment]
[main.zip](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/files/11581595/main.zip)

**Comment by xiatian12345** [comment]
并行下载数量问题解决了，但是有可能会产生新的超时错误

2023-05-27 22:01:11,787 - DEBUG - 三国演义312经过三次重试后下载失败！
2023-05-27 22:01:11,788 - DEBUG - 三国演义283第3次下载失败！
2023-05-27 22:01:11,788 - DEBUG - Traceback (most recent call last):
  File "/Users/xiatian/soft/Ximalaya-Downloader/main.py", line 198, in async_get_sound
    async with session.get(sound_url, headers=self.default_headers, timeout=120) as response:
  File "/Users/xiatian/.pyenv/versions/3.7.15/lib/python3.7/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/xiatian/.pyenv/versions/3.7.15/lib/python3.7/site-packages/aiohttp/client.py", line 637, in _request
    break
  File "/Users/xiatian/.pyenv/versions/3.7.15/lib/python3.7/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

**Comment by xiatian12345** [comment]
async with session.get(sound_url, headers=self.default_headers, timeout=360) as response:#增大超时时长暂时解决了问题

**Comment by Diaoxiaozhang** [comment]
我之后搞个根据下载音频量确定超时时间吧
