### ISSUE TITLE
最新发布包 下载专辑时下载任务线程好像太高了 大部分都失败了

### ISSUE THREAD

**Issue by dixtdf** [Diaoxiaozhang/Ximalaya-Downloader#2]
失败后再次尝试会

Traceback (most recent call last):
  File "console-version.py", line 2, in <module>
  File "main.py", line 512, in run
  File "asyncio\base_events.py", line 647, in run_until_complete
  File "main.py", line 276, in get_selected_vip_sounds
  File "main.py", line 217, in async_get_encrypted_url
KeyError: 'trackInfo'
[8260] Failed to execute script 'console-version' due to unhandled exception!

breadcrumbs.ts:111 
        
       [Player Error] player catch error:  Error: innert Error: errorCode: 0; errorMsg: 当前的声音的地址无效
       
是不是下载太多了，然后当天就封了

[Player Error] player catch error:  今天操作太频繁啦，可以明天再试试哦~

**Comment by Diaoxiaozhang** [comment]
这个是喜马拉雅官方对vip音频的接口的限制，不是封号，第二天就会恢复的。这个我暂时也没办法，这两天我去研究一下别的接口。

**Comment by Diaoxiaozhang** [comment]
找到了电脑客户端的一个vip音频接口，意外的顺利，不出意外下个版本就能修复这个问题。
