### ISSUE TITLE
VIP专辑下载提示错误

### ISSUE THREAD

**Issue by LEI-RD024** [Diaoxiaozhang/Ximalaya-Downloader#47]
![xmly_d1](https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/38022202/b5358cae-ec3c-4901-a960-d074a084944d)

**Comment by LEI-RD024** [comment]
2024-03-28 16:19:54,955 - DEBUG - 开始解析ID为39959280的专辑
2024-03-28 16:19:56,867 - DEBUG - ID为39959280的专辑解析成功
2024-03-28 16:19:56,867 - DEBUG - 开始判断ID为39959280的专辑的类型
2024-03-28 16:19:57,236 - DEBUG - ID为39959280的专辑判断类型成功！
2024-03-28 16:20:03,183 - DEBUG - ID为322279919的声音解析失败！
2024-03-28 16:20:03,183 - DEBUG - Traceback (most recent call last):
  File "main.py", line 131, in async_analyze_sound
KeyError: 'trackInfo'

2024-03-28 16:20:03,183 - DEBUG - ID为324270747的声音解析失败！
2024-03-28 16:20:03,183 - DEBUG - Traceback (most recent call last):
  File "main.py", line 131, in async_analyze_sound
KeyError: 'trackInfo'

**Comment by Diaoxiaozhang** [comment]
这是vip音频下载数达到每日上限了，等一天就好了，另外建议更新到最新版，最新版遇到这个问题不会报错而是会提示到达上限

**Comment by iapeng** [comment]
很多只下载了文件名，而音频大小是空的

**Comment by Diaoxiaozhang** [comment]
> 很多只下载了文件名，而音频大小是空的

更新到最新版，把空文件删掉重新下一遍

**Comment by LEI-RD024** [comment]
tks ...
很可能是提示不准确
