### ISSUE TITLE
建议加入重试功能，或除了访问指定外，还可以指定具体的id列表下载

### ISSUE THREAD

**Issue by xyxy** [Diaoxiaozhang/Ximalaya-Downloader#48]
建议加入重试功能
<img width="297" alt="image" src="https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/2542438/78a59aa4-c27f-438b-a70d-7debef55e9c5">

除了访问指定外，建议还可以指定具体的id列表下载
<img width="556" alt="image" src="https://github.com/Diaoxiaozhang/Ximalaya-Downloader/assets/2542438/b410a065-7239-402a-ac8c-8bf1efe14983">

**Comment by Diaoxiaozhang** [comment]
重试功能是有的，如果版本是最新版且没有超过单日付费音频下载上限的情况下还出现这种大量下载失败的情况的话把日志发来看看，指定具体的id列表下载的功能会考虑加入

**Comment by xyxy** [comment]
> 重试功能是有的，如果版本是最新版本且没有超过单日付费音频下载上限的情况下还出现这种大量下载失败的情况的话把日志发来看看，指定具体的id列表下载的功能会考虑加入

我git 克隆下来后，用python cli.py 运行的，没找到日志，可能是被清理掉了，不过应该可以通过下载整个专辑6443741复现

**Comment by Diaoxiaozhang** [comment]
我尝试下载没有出现错误，你要不重试一遍再把日志发一下吧

**Comment by chensiluo** [comment]
> 我尝试下载没有出现错误，你要不重试一遍再把日志发一下吧

2024-04-08 22:14:51,153 - DEBUG - 0926-93、抖音购物车大调整可能会带来哪些影响？从业者怎么看？第1次下载失败！
2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
  File "main.py", line 219, in async_get_sound
  File "aiohttp\client.py", line 1141, in __aenter__
  File "aiohttp\client.py", line 637, in _request
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

2024-04-08 22:14:51,153 - DEBUG - 0925-94、10位百万级大咖实操心得分享，做好抖音记住这5点就够了！第1次下载失败！
2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
  File "main.py", line 219, in async_get_sound
  File "aiohttp\client.py", line 1141, in __aenter__
  File "aiohttp\client.py", line 637, in _request
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

2024-04-08 22:14:51,153 - DEBUG - 0924-95、商家快速抢占抖音销售渠道之【达人推网红带货平台】第1次下载失败！
2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
  File "main.py", line 219, in async_get_sound
  File "aiohttp\client.py", line 1141, in __aenter__
  File "aiohttp\client.py", line 637, in _request
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

2024-04-08 22:14:51,153 - DEBUG - 0923-96、企业最关心的抖音蓝V认证权益都在这里了（企业必学）第1次下载失败！
2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
  File "main.py", line 219, in async_get_sound
  File "aiohttp\client.py", line 1141, in __aenter__
  File "aiohttp\client.py", line 637, in _request
  File "aiohttp\helpers.py", line 721, in __exit__
asyncio.exceptions.TimeoutError

**Comment by Diaoxiaozhang** [comment]
> > 我尝试下载没有出现错误，你要不重试一遍再把日志发一下吧
> 
> 2024-04-08 22:14:51,153 - DEBUG - 0926-93、抖音购物车大调整可能会带来哪些影响？从业者怎么看？第1次下载失败！
> 2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
>   File "main.py", line 219, in async_get_sound
>   File "aiohttp\client.py", line 1141, in __aenter__
>   File "aiohttp\client.py", line 637, in _request
>   File "aiohttp\helpers.py", line 721, in __exit__
> asyncio.exceptions.TimeoutError
> 
> 2024-04-08 22:14:51,153 - DEBUG - 0925-94、10位百万级大咖实操心得分享，做好抖音记住这5点就够了！第1次下载失败！
> 2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
>   File "main.py", line 219, in async_get_sound
>   File "aiohttp\client.py", line 1141, in __aenter__
>   File "aiohttp\client.py", line 637, in _request
>   File "aiohttp\helpers.py", line 721, in __exit__
> asyncio.exceptions.TimeoutError
> 
> 2024-04-08 22:14:51,153 - DEBUG - 0924-95、商家快速抢占抖音销售渠道之【达人推网红带货平台】第1次下载失败！
> 2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
>   File "main.py", line 219, in async_get_sound
>   File "aiohttp\client.py", line 1141, in __aenter__
>   File "aiohttp\client.py", line 637, in _request
>   File "aiohttp\helpers.py", line 721, in __exit__
> asyncio.exceptions.TimeoutError
> 
> 2024-04-08 22:14:51,153 - DEBUG - 0923-96、企业最关心的抖音蓝V认证权益都在这里了（企业必学）第1次下载失败！
> 2024-04-08 22:14:51,153 - DEBUG - Traceback (most recent call last):
>   File "main.py", line 219, in async_get_sound
>   File "aiohttp\client.py", line 1141, in __aenter__
>   File "aiohttp\client.py", line 637, in _request
>   File "aiohttp\helpers.py", line 721, in __exit__
> asyncio.exceptions.TimeoutError

请提供完整文件
