### ISSUE TITLE
ubuntu18.04报错

### ISSUE THREAD

**Issue by fangpidedongsun** [Diaoxiaozhang/Ximalaya-Downloader#54]
请选择您想要下载的音质：（直接回车默认为普通音质）
0. 低音质
1. 普通音质
2. 高音质（如果没有高音质则将下载普通音质）
2
Traceback (most recent call last):
  File "cli.py", line 183, in <module>
    loop.run_until_complete(ximalaya.get_selected_sounds(sounds, album_name, start, end, headers, int(choice), number, path))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/root/ximalaya/xxx/main.py", line 244, in get_selected_sounds
    tasks.append(asyncio.create_task(self.async_analyze_sound(sound_id, session, headers)))
AttributeError: module 'asyncio' has no attribute 'create_task'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f874f14aef0>

**Comment by Diaoxiaozhang** [comment]
这个应该是asyncio版本太老
