### ISSUE TITLE
专辑里面有些声音无法下载

### ISSUE THREAD

**Issue by jasoworld** [Diaoxiaozhang/Ximalaya-Downloader#9]
专辑里面有些声音无法下载。单独下载报错。请帮忙看看
```
请输入声音ID或链接：
https://www.ximalaya.com/sound/47736239
声音名第3集：舌头会跳舞？（1），判断为已购付费声音或vip免费声音，正在开始下载……
ID为47736239的vip声音解析失败！
Traceback (most recent call last):
  File "D:\GitHub\Ximalaya-Downloader\console-version.py", line 2, in <module>
    main.ConsoleVersion().run()
  File "D:\GitHub\Ximalaya-Downloader\main.py", line 555, in run
    self.ximalaya.get_vip_sound(sound_name, sound_id, headers)
  File "D:\GitHub\Ximalaya-Downloader\main.py", line 343, in get_vip_sound
    sound_url = self.decrypt_url(encrypted_url)
  File "D:\GitHub\Ximalaya-Downloader\main.py", line 235, in decrypt_url
    ciphertext = base64.urlsafe_b64decode(ciphertext + '=' * (4 - len(ciphertext) % 4))
TypeError: object of type 'bool' has no len()
```

**Comment by Diaoxiaozhang** [comment]
应该是达到每日能够下载vip音频的上限了，第二天再试吧
