### ISSUE TITLE
用0.4.4版本下载时，输入cookie后显示拒绝连接

### ISSUE THREAD

**Issue by yosaku01** [Diaoxiaozhang/Ximalaya-Downloader#91]
2024-10-08 21:27:16,004 - DEBUG - 无法获取喜马拉雅用户数据！
2024-10-08 21:27:16,006 - DEBUG - Traceback (most recent call last):
  File "urllib3\connection.py", line 200, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 776, in urlopen
  File "urllib3\connectionpool.py", line 1041, in _prepare_proxy
  File "urllib3\connection.py", line 604, in connect
  File "urllib3\connection.py", line 215, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001EDB96583D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EDB96583D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.ximalaya.com', port=443): Max retries exceeded with url: /revision/my/getCurrentUserInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EDB96583D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 395, in judge_cookie
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.ximalaya.com', port=443): Max retries exceeded with url: /revision/my/getCurrentUserInfo (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EDB96583D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

**Comment by yosaku01** [comment]
全局设置了代理服务器导致的
